FROM python:3.8.3-slim-buster

# set work directory
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
# install psycopg2 dependencies
RUN apt-get update \
    && apt-get -y install libpq-dev gcc \
    && pip install psycopg2
RUN apt install -y netcat

# install dependencies
# RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt
# copy entrypoint.sh
COPY ./entrypoint.sh .

# copy project
COPY . .
RUN chmod 755 /usr/src/app/entrypoint.sh
# run entrypoint.sh
ENTRYPOINT ["sh", "/usr/src/app/entrypoint.prod.sh"]
EXPOSE 8001
COPY . /usr/src/app

# run server
CMD ["/usr/src/app/entrypoint.prod.sh"]



