version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 8001:8001
    volumes:
      - ./:/usr/src/app
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
    networks:
      my-network:
        aliases:
          - app

  db:
    image: postgres:10-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env.db
    networks:
      my-network:
        aliases:
          - db

  redis:
    image: "redis:alpine"
    ports: 
    - 6379:6379
    networks:
      my-network:
        aliases:
          - redis

volumes:
  postgres_data:

networks:
    my-network:
