{'social_django.view_usersocialauth',
 'main.add_invoice', 'auth.view_permission',  'sessions.add_session', 'main.change_till',
 'main.add_store', 'main.change_suppliedby', 'main.add_dispatch', 'main.delete_recipt',
 'social_django.view_association', 'sessions.delete_session',
 'main.add_recipt', 'admin.change_logentry', 'auth.change_group',
 'main.delete_item', 'social_django.change_partial', 'main.add_item',
 'social_django.delete_association', 'social_django.add_association',
 'social_django.add_nonce', 'main.change_recipt', 'main.change_item',
 'main.change_dispatchedby', 'social_django.change_association',
 'main.delete_dispatchedby', 'main.view_user', 'main.add_supplier',
 'main.view_suppliedby', 'admin.delete_logentry',
 'social_django.delete_usersocialauth', 'main.add_outlet',
    'main.delete_invoice', 'contenttypes.change_contenttype',
 'main.change_supplier', 'auth.view_group', 'admin.view_logentry',
 'social_django.change_code', 'social_django.delete_partial',
 'social_django.change_nonce', 'main.change_invoice', 'main.delete_store',
 'main.view_outlet', 'sessions.view_session',
    'sessions.change_session', 'social_django.view_partial',
 'social_django.delete_nonce', 'main.add_till', 'main.change_store',
 'main.delete_suppliedby', 'main.view_dispatchedby', 'main.change_dispatch',
 'contenttypes.add_contenttype', 'main.view_supplier', 'social_django.add_partial',
 'social_django.change_usersocialauth', 'contenttypes.view_contenttype',
 'main.delete_outlet', 'main.change_purchase', 'main.view_invoice',
 'social_django.view_code', 'social_django.add_usersocialauth',
 'auth.delete_permission', 'main.add_purchase', 'social_django.view_nonce',
 'main.view_store', 'main.view_recipt', 'auth.change_permission',
 'main.delete_supplier', 'admin.add_logentry', 'main.view_till',
 'auth.delete_group', 'main.delete_till', 'auth.add_permission',
 'main.delete_purchase', 'main.view_dispatch', 'main.add_dispatchedby',
 'main.delete_user', 'main.view_item', 'main.add_user', 'social_django.delete_code',
 'contenttypes.delete_contenttype', 'social_django.add_code', 'auth.add_group',
 'main.change_outlet', 'main.add_suppliedby', 'main.view_purchase', 'main.change_user',
  'main.delete_dispatch'}
