# Generated by Django 3.1.6 on 2021-02-04 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=255, null=True, verbose_name='first name')),
                ('last_name', models.CharField(max_length=255, verbose_name='last name')),
                ('gender', models.CharField(max_length=6, verbose_name='gender')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date joined')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date and Time Modified')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date and Time')),
                ('pic', models.ImageField(upload_to='items/', verbose_name='Picture')),
                ('quantity', models.IntegerField(default=10, verbose_name='Quantity')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30, unique=True, verbose_name='Title')),
                ('description', models.CharField(max_length=100, unique=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['-date_modified'],
            },
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date and Time Modified')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date and Time')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Address')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Name')),
                ('description', models.CharField(max_length=100, unique=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Outlet',
                'verbose_name_plural': 'Outlets',
                'ordering': ['-date_modified'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date and Time Modified')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date and Time')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Address')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Name')),
                ('description', models.CharField(max_length=100, unique=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
                'ordering': ['-date_modified'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date and Time')),
                ('initial_quatity', models.IntegerField(default=10, verbose_name='Initial Quantity')),
                ('quantity_added', models.IntegerField(default=10, verbose_name='Quantity')),
                ('new_quatity', models.IntegerField(default=10, verbose_name='New Quantity')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('increase', 'Increase'), ('decrease', 'Decrease')], default='add', max_length=30, verbose_name='Transaction Type')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.item')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.store')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Till',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date and Time')),
                ('till_number', models.CharField(blank=True, max_length=500, null=True, verbose_name='Till Number')),
                ('description', models.CharField(max_length=100, unique=True, verbose_name='Description')),
                ('outlet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.outlet')),
            ],
            options={
                'verbose_name': 'Till',
                'verbose_name_plural': 'Tills',
                'ordering': ['-till_number'],
            },
        ),
        migrations.CreateModel(
            name='SuppliedBy',
            fields=[
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date and Time')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date and Time')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('outlet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.outlet')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.store')),
            ],
            options={
                'ordering': ['-date_modified'],
            },
        ),
        migrations.CreateModel(
            name='Recipt',
            fields=[
                ('ref_number', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('date_of_generated', models.DateTimeField(auto_now_add=True, verbose_name='Date and Time ')),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.transaction')),
            ],
            options={
                'ordering': ['date_of_generated'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('ref_number', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('date_of_generated', models.DateTimeField(auto_now_add=True, verbose_name='Date and Time ')),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.transaction')),
            ],
            options={
                'ordering': ['date_of_generated'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.store'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
