# Generated by Django 3.1.6 on 2021-02-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='barcode',
            field=models.CharField(default=123456789123, max_length=19, unique=True, verbose_name='Barcode'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('Q', 'Rather Not Say')], max_length=1, verbose_name='gender'),
        ),
    ]
