# Generated by Django 3.1.6 on 2021-02-07 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.RemoveField(
            model_name='item',
            name='pic',
        ),
    ]
