# Generated by Django 3.1.6 on 2021-02-09 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210207_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='quantity_added',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='suppliedby',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.transaction'),
        ),
    ]
