# Generated by Django 3.1.6 on 2021-02-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210219_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='re_order_level',
            field=models.IntegerField(default=5, verbose_name='Re-order Level'),
        ),
    ]
