# Generated by Django 3.1.6 on 2021-02-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210219_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Description'),
        ),
    ]
