# Generated by Django 3.1.6 on 2021-02-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210224_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='money_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='item',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchase',
            name='money_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
